listener {
  on-timeout=brightnessctl -c backlight s 40%- -s
  on-resume=brightnessctl -c backlight -r
  timeout=780 # 13 minutes
}

listener {
  on-timeout=niri msg action power-off-monitors
  on-resume=niri msg action power-on-monitors
  timeout=810 # 13.5 minutes
}

listener {
  on-timeout=hyprlock -g 30
  timeout=840 # 14 minutes
}

listener {
  on-timeout=systemctl sleep
  condition_cmd=~/.config/hypr/can_suspend.sh
  timeout=900 # 15 minutes
  condition_retry = 60
}

# Additional shorter timeouts for when the lockscreen is active
listener {
  on-timeout=brightnessctl -c backlight s 40%- -s
  on-resume=brightnessctl -c backlight -r
  condition_cmd=[[ -n $(pgrep -l hyprlock) ]]
  timeout=240 # 4 minutes
}

listener {
  on-timeout=niri msg action power-off-monitors
  on-resume=niri msg action power-on-monitors
  condition_cmd=[[ -n $(pgrep -l hyprlock) ]]
  timeout=270 # 4.5 minutes
}

listener {
  on-timeout=systemctl sleep
  condition_cmd=[[ -n $(pgrep -l hyprlock) ]] && ~/.config/hypr/can_suspend.sh
  timeout=300 # 5 minutes
  condition_retry = 30
}
