# Base16 Oxocarbon - alacritty color config
# adapted from https://github.com/nyoom-engineering/base16-oxocarbon and 
# https://github.com/aarowill/base16-alacritty/blob/master/templates/default.mustache

import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
  #"~/.config/alacritty/oxocarbon.toml"
]

[colors]
draw_bold_text_with_bright_colors = false

[window]
opacity = 0.6


[shell]
program = '/usr/bin/fish'
