import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
  #"~/.config/alacritty/oxocarbon.toml"
]

[colors]
draw_bold_text_with_bright_colors = false

[window]
opacity = 0.6


[shell]
program = '/usr/bin/fish'

[font]
normal = { family = "Fira Code", style = "Regular"}
bold = { family = "Fira Code", style = "Bold"}
italic = { family = "Fira Code", style = "Italic"}
bold_italic = { family = "Fira Code", style = "Bold Italic"}
